context:
  version: 0.1a9

package:
  name: rpi-libcamera
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/r/rpi-libcamera/rpi_libcamera-${{ version }}.tar.gz
    sha256: 26b4d36256ffb17f845b52814d1fd9f36512c6ded2477e2706d7555c5f4cd4a5

build:
  script: ${{ PYTHON }} -m pip install .
  number: 0
  skip:
    - win or osx

requirements:
  host:
    - python
    - meson-python
    - pyyaml
    - pybind11
    - jinja2
    - ply
    - pip
    - setuptools
    - libcamera
  run:
    - python
    - libcamera

tests:
  - python:
      imports:
        - rpi-libcamera
      pip_check: true

about:
  homepage: https://github.com/raspberrypi/pylibcamera
  summary: libcamera python bindings
  description: |
    This package is for the libcamera python bindings only.
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
