# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: dearpygui
  version: 1.7

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/hoffstadt/DearPyGui/archive/v${{ version }}.tar.gz
  sha256: 9be64c73f684b037f3e5231a0f22eda28b09fc347ece31387773a189953cc9bc

build:
  script: ${{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - ${{ cdt('libx11-devel') }}
    - cmake
    - if: not win
      then:
        - make
      else:
        - ninja
  host:
    - pip
    - python
    - setuptools
    - mesalib
    - if: linux
      then:
        - libgl-devel
        - libxcrypt
    - xorg-xorgproto
    - xorg-libx11
    - xorg-libxrandr
    - xorg-libxinerama
    - xorg-libxcursor
    - xorg-libxi
  run:
    - python

tests:
  - python:
      imports:
        - dearpygui

about:
  homepage: https://github.com/hoffstadt/DearPyGui
  documentation: https://dearpygui.readthedocs.io/en/latest/
  license: Apache-2.0 AND BSD-4-Clause AND MIT AND AGPL-3.0-only
  license_file:
    - LICENSE
    - thirdparty/cpython/LICENSE
    - thirdparty/cpython/Doc/copyright.rst
    - thirdparty/cpython/Doc/license.rst
    - thirdparty/cpython/Mac/BuildScript/resources/License.rtf
    - thirdparty/cpython/Modules/expat/COPYING
    - thirdparty/cpython/Modules/_ctypes/darwin/LICENSE
    - thirdparty/cpython/Modules/_ctypes/libffi_osx/LICENSE
    - thirdparty/cpython/Tools/msi/bundle/bootstrap/LICENSE.txt
    - thirdparty/DearPyGui_Ext/LICENSE
    - thirdparty/glfw/LICENSE.md
    - thirdparty/imgui/LICENSE.txt
    - thirdparty/imgui/examples/libs/glfw/COPYING.txt
    - thirdparty/ImGuiFileDialog/LICENSE
    - thirdparty/imnodes/LICENSE.md
    - thirdparty/implot/LICENSE
  summary: A fast and powerful Graphical User Interface Toolkit for Python with minimal dependencies

extra:
  recipe-maintainers:
    - carlodri
