{% set name = "kmsxx" %}
{% set version = "0.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/tomba/kmsxx.git
  git_rev: master

build:
  number: 0
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_subpackage('kmsxx', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - meson
    - ninja
    - pkg-config
  host:
    - python
    - xorg-libx11
    - xorg-xproto
    - xorg-kbproto
    - pybind11
    - fmt
    - libdrm
  run:
    - python

test:
  imports:
    - pykms
  commands:
    - test -f $PREFIX/lib/libkms++.so.0
    - test -f $PREFIX/lib/libkms++util.so.0
    - test -x $PREFIX/bin/kmsblank
    - test -x $PREFIX/bin/kmscube
    - kmscapture --help

about:
  home: https://github.com/tomba/kmsxx
  license: MIT
  license_file: LICENSE
  summary: "DRM/KMS library for Linux with Python bindings"

extra:
  recipe-maintainers:
    - carlodri
