{% set name = "kmsxx" %}
{% set version = "0.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/tomba/kmsxx.git
  git_rev: master

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - meson
    - ninja
    - pkg-config
  host:
    - python
    - pybind11
    - fmt
  run:
    - python

test:  # will add more later
  imports:
    - kms

about:
  home: https://github.com/tomba/kmsxx
  license: MIT
  license_file: LICENSE
  summary: "DRM/KMS library for Linux with Python bindings"

extra:
  recipe-maintainers:
    - carlodri
