{% set name = "kmsxx" %}
{% set version = "0.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/tomba/kmsxx.git
  # pin to this while upstream handles https://github.com/tomba/kmsxx/issues/83
  git_rev: 1813adae89203e15fc60344864fc2ca0d3c75e07

build:
  number: 0
  skip: true  # [win or osx]
  # ABI compatibility is not known...
  run_exports:
    - {{ pin_subpackage('kmsxx', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - meson
    - ninja
    - pkg-config
  host:
    - python
    - pybind11
    - fmt
    - libdrm
  run:
    - python

test:
  imports:
    - pykms
  commands:
    - test -f $PREFIX/lib/libkms++.so.0
    - test -f $PREFIX/lib/libkms++util.so.0
    - test -x $PREFIX/bin/kmsblank
    - test -x $PREFIX/bin/kmstest
    - test -x $PREFIX/bin/kmsprint
    - test -x $PREFIX/bin/fbtest

about:
  home: https://github.com/tomba/kmsxx
  license: MIT
  license_file: LICENSE
  summary: "DRM/KMS library for Linux with Python bindings"

extra:
  recipe-maintainers:
    - carlodri
