context:
  version: 0.3.25

package:
  name: picamera2
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/picamera2/picamera2-${{ version }}.tar.gz
  sha256: cacf3c40b8240f0b8020269ce966ba911c70fe987c4a2bf2fb969ce34d74669a

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  skip:
  - win
  - osx

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - libcamera
    - pidng
    - av
    - jsonschema
    - libarchive-c
    - numpy
    - piexif
    - pillow
    - python-prctl
    - simplejpeg
    - tqdm
    - v4l2-python3
  # - pyqt5  # extra == "gui"
  # - pyopengl  # extra == "gui"

tests:
- python:
    imports:
    - picamera2
    pip_check: true

about:
  homepage: https://github.com/RaspberryPi/picamera2
  summary: The libcamera-based Python interface to Raspberry Pi cameras, based on the original Picamera library
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
  - carlodri
