context:
  version: 0.0.1a20

package:
  name: ty
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/t/ty/ty-${{ version }}.tar.gz
    sha256: 933b65a152f277aa0e23ba9027e5df2c2cc09e18293e87f2a918658634db5f15

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python >=3.8
    - maturin>=1.0,<2.0
    - pip
  run:
    - python >=3.8

tests:
  - python:
      imports:
        - ty
      pip_check: true

about:
  homepage: https://github.com/astral-sh/ty/
  summary: An extremely fast Python type checker, written in Rust.
  license_file: LICENSE
  license: MIT

extra:
  recipe_maintainers:
    - carlodri
