context:
  version: 0.3.5

package:
  name: v4l2-python3
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/v/v4l2-python3/v4l2_python3-${{ version }}.tar.gz
  sha256: e7e24739c1816d64a82929b81781ada4e5640974157a39585ad2e02dfdb102fd

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  skip:
  - win
  - osx

requirements:
  host:
  - python
  - pip
  - setuptools
  run:
  - python

tests:
- python:
    imports:
    - v4l2-python3
    pip_check: true

about:
  homepage: https://pypi.org/project/v4l2-python3/
  summary: Python bindings for the v4l2 userspace api.
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
  - carlodri
