context:
  version: 0.0.4

package:
  name: videodev2
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/v/videodev2/videodev2-${{ version }}.tar.gz
  sha256: c34ba70491d148c23a08cbacd8efabeb413cff5baa943a7548ac4abd1eb19e2a

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  skip:
  - win
  - osx

requirements:
  host:
  - python
  - pip
  - setuptools
  run:
  - python

tests:
- python:
    imports:
    - videodev2
    pip_check: true

about:
  homepage: https://github.com/raspberrypi/py-videodev2
  summary: Python ctypes bindings for Video4Linux2 (V4L2) API
  license: BSD-3-Clause

extra:
  recipe-maintainers:
  - carlodri
